name = "post-stats"
main = "build/worker/shim.mjs"
compatibility_date = "2024-01-01"

[build]
command = "cargo install worker-build && worker-build --release"

[[kv_namespaces]]
binding = "POST_STATS"
id = "dfae1bc83c844cac8541f1488cd435b6"
